baseline: Just things
theme:
  - hyde
  - netlify
  - netlify-cms
keywords:
  - Cecil
  - Static Site Generator
  - SSG
author: Arnaud Ligny
description: Powered by Cecil.
date:
  format: j F Y
  timezone: Europe/London
hyde:
  sidebar:
    sticky: true
  theme: ""
  reverse: false
title: pmercs
baseurl: /
canonicalurl: true
